apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: mzukwdw90-nodejs 
  janus-idp.io/tekton: mzukwdw90-nodejs
  backstage.io/kubernetes-id: mzukwdw90-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mzukwdw90-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml